server {

    listen 8099;
    listen [::]:8099;
    allow  172.30.32.2;
    deny   all;

    # Send logs to the Docker container's stdout/stderr for Home Assistant to capture.
    access_log /dev/stdout;
    error_log /dev/stderr;

    # FIXME: this is barebones from https://developers.home-assistant.io/docs/add-ons/presentation#ingress
    # How to proxy traffic to frontend base bath correctly?
    location / {
        proxy_pass http://127.0.0.1:2021;
    }
}
